# Generated by Django 6.0 on 2025-12-25 14:36

import account.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=120)),
                ('position', models.CharField(blank=True, max_length=120)),
                ('bio', models.TextField(blank=True)),
                ('twitter', models.URLField(blank=True, validators=[account.validators.validate_twitter_url])),
                ('instagram', models.URLField(blank=True, validators=[account.validators.validate_instagram_url])),
                ('linkedin', models.URLField(blank=True, validators=[account.validators.validate_linkedin_url])),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name'],
                'indexes': [models.Index(fields=['display_name'], name='account_aut_display_3ff2d4_idx')],
            },
        ),
    ]
