# Generated by Django 6.0 on 2025-12-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_top_news',
            field=models.BooleanField(default=False),
        ),
    ]
